<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '20b90382c38d60415ccf369435d40bde',
  'DATABASE_URL' => 'mysql://xutmwoiu_obscury:lafiabruno000272@ftp.obscury.com:3306/xutmwoiu_obscury',
  'MAILER_URL' => 'smtp://mail.obscury.com:465?encryption=ssl&auth_mode=login&username=contact@obscury.com&password=lafiabruno000272',
);
